import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x8fc9ed); scene.fog=new THREE.Fog(0x8fc9ed,180,900);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,1800); camera.position.set(14,12,20);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; document.body.appendChild(renderer.domElement); renderer.domElement.id='game';
const controls=new OrbitControls(camera,renderer.domElement); controls.enablePan=false; controls.enableDamping=true; controls.minDistance=7; controls.maxDistance=28; controls.maxPolarAngle=Math.PI*.47; controls.target.set(0,1,0);
scene.add(new THREE.HemisphereLight(0xeaf8ff,0x506040,2.1)); const sun=new THREE.DirectionalLight(0xffffff,3); sun.position.set(120,180,80); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const world=new THREE.Group(); scene.add(world); const colliders=[]; const interactables=[]; const cars=[]; const npcs=[];
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.8,metalness:.05})} function box(w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.castShadow=true;m.receiveShadow=true;return m}
function label(text,pos){const cv=document.createElement('canvas'),cx=cv.getContext('2d');cv.width=512;cv.height=96;cx.fillStyle='rgba(4,12,20,.78)';cx.roundRect(4,4,504,88,18);cx.fill();cx.fillStyle='white';cx.font='bold 34px system-ui';cx.textAlign='center';cx.fillText(text,256,61);const t=new THREE.CanvasTexture(cv);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.scale.set(7,1.32,1);s.position.copy(pos);world.add(s);return s}
function road(x,z,w,d){const r=box(w,.06,d,0x30353b);r.position.set(x,.03,z);world.add(r);for(let i=-w/2+8;i<w/2-2;i+=12){const line=box(5,.065,.18,0xe7d98b);line.position.set(x+i,.07,z);world.add(line)}return r}
function roadZ(x,z,w,d){const r=box(w,.06,d,0x30353b);r.position.set(x,.03,z);world.add(r);for(let i=-d/2+8;i<d/2-2;i+=12){const line=box(.18,.065,5,0xe7d98b);line.position.set(x,.07,z+i);world.add(line)}return r}
function sidewalk(x,z,w,d){const s=box(w,.16,d,0xb7b1a4);s.position.set(x,.08,z);world.add(s)}
function tree(x,z){const g=new THREE.Group();const trunk=box(.55,2,.55,0x6b432b);trunk.position.y=1;g.add(trunk);const crown=new THREE.Mesh(new THREE.SphereGeometry(2.1,14,10),mat(0x2f7a43));crown.position.y=3.1;crown.castShadow=true;g.add(crown);g.position.set(x,0,z);world.add(g)}
function building(name,x,z,w,d,h,color,interior=false){const g=new THREE.Group();g.position.set(x,0,z);const b=box(w,h,d,color);b.position.y=h/2;g.add(b);const roof=box(w+.35,.45,d+.35,0x40434a);roof.position.y=h+.2;g.add(roof);for(let ix=-w/2+3;ix<w/2-1;ix+=4){for(let iz=-d/2+.1;iz<d/2;iz+=4){const win=box(1.8,1.8,.08,0x8ed8ef);win.position.set(ix,h*.62,iz-d/2-.05);g.add(win)}}world.add(g);label(name,new THREE.Vector3(x,h+2,z)); if(interior){const door=box(2.2,3,.18,0x292016);door.position.set(x,1.5,z-d/2-.11);world.add(door);interactables.push({pos:new THREE.Vector3(x,0,z-d/2-2.5),type:'house',name})} return g}
function room(x,z,w,d,h,c){const floor=box(w,.1,d,0x7c6b59);floor.position.set(x,.05,z);world.add(floor);const back=box(w,h,.12,c);back.position.set(x,h/2,z+d/2);world.add(back);const l=box(.12,h,d,c);l.position.set(x-w/2,h/2,z);world.add(l);const r=box(.12,h,d,c);r.position.set(x+w/2,h/2,z);world.add(r)}
function makeHouseInterior(){const base=new THREE.Group();base.position.set(38,0,38);const floor=box(18,.2,14,0x806c58);floor.position.y=.1;base.add(floor);const walls=[[18,3,.2,0xd7d1c4,0,1.5,-7],[.2,3,14,0xd7d1c4,-9,1.5,0],[.2,3,14,0xd7d1c4,9,1.5,0]];walls.forEach(a=>{const q=box(a[0],a[1],a[2],a[3]);q.position.set(a[4],a[5],a[6]);base.add(q)});const kitchen=box(7,1,2,0x6b4a35);kitchen.position.set(-4,.7,-3.8);base.add(kitchen);const sofa=box(5,1.2,1.8,0x4f6573);sofa.position.set(4,.8,3);base.add(sofa);const bed=box(5,.8,3,0xb78c78);bed.position.set(4,.55,-3);base.add(bed);const table=box(2.5,.9,2,0x6c4c31);table.position.set(-3,.5,2.5);base.add(table);world.add(base);label('House Interior',new THREE.Vector3(38,8,38))}
// Large continuous neighbourhood: roads, footpaths, green strips and blocks
road(0,0,900,14); roadZ(0,0,14,900); road(0,120,900,12); road(0,-120,900,12); roadZ(120,0,12,900); roadZ(-120,0,12,900);
for(let x=-420;x<=420;x+=30){sidewalk(x,10,26,3);sidewalk(x,-10,26,3)} for(let z=-420;z<=420;z+=30){sidewalk(10,z,3,26);sidewalk(-10,z,3,26)}
for(let x=-400;x<=400;x+=40)for(let z=-400;z<=400;z+=40){if(Math.abs(x)<30||Math.abs(z)<30)continue;tree(x,z)}
// Core buildings and services
building('Dream School',-65,-65,30,22,13,0xd9a34f); building('City Hospital',65,-65,34,24,15,0xe7e7e4); building('City Office',-65,65,30,22,14,0x6b91ba); building('Dream Market',65,65,30,22,10,0xb96b4e); building('Apartment Block',-165,-65,32,24,22,0x8b9bb3); building('University',165,-65,40,28,17,0xc9b35e); building('Police Station',-165,65,30,22,11,0x53718f); building('Fire Station',165,65,32,24,11,0xb95c4d); building('Your House',38,38,18,14,7,0xd6b08a,true); makeHouseInterior();
// player: simple human rig with animated legs/arms
const player=new THREE.Group(); const body=box(1.1,1.6,.65,0x2e75b6);body.position.y=2.05;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.43,18,14),mat(0xd6a47d));head.position.y=3.25;head.castShadow=true;player.add(head);const legs=[];const arms=[];for(const sx of [-.3,.3]){const leg=box(.28,1.25,.32,0x26384c);leg.position.set(sx,0.72,0);player.add(leg);legs.push(leg);const arm=box(.25,1.2,.25,0xd6a47d);arm.position.set(sx*2,2.05,0);player.add(arm);arms.push(arm)}player.position.set(0,0,35);world.add(player);
function npc(x,z,c=0x8a4fb0){const g=new THREE.Group();const b=box(.9,1.35,.55,c);b.position.y=1.75;g.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.36,14,10),mat(0xb87958));h.position.y=2.8;g.add(h);g.position.set(x,0,z);world.add(g);npcs.push({g,base:x,z,phase:Math.random()*6.28,speed:.7+Math.random()*.5});} for(let i=0;i<16;i++)npc(-100+i*12,22+(i%3)*5, i%2?0x8b5ca8:0x4d8c73);
function car(x,z,rot=0,c=0xc0392b,ai=true){const g=new THREE.Group();const ch=box(2.2,.65,4.4,c);ch.position.y=.7;g.add(ch);const cabin=box(1.75,.65,2.1,0x273746);cabin.position.y=1.25;cabin.position.z=-.1;g.add(cabin);for(const sx of [-1,1])for(const sz of [-1,1]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.25,12),mat(0x161616));w.rotation.z=Math.PI/2;w.position.set(sx*1.15,.45,sz*1.45);g.add(w)}g.position.set(x,.0,z);g.rotation.y=rot;world.add(g);cars.push({g,axis:Math.abs(Math.sin(rot))>.5?'z':'x',dir:rot?1:-1,speed:ai?7+Math.random()*5:0,ai});return g} for(let i=0;i<14;i++)car(-390+i*55,-4,0,[0x2f80ed,0xe67e22,0x27ae60,0x9b59b6][i%4],true);for(let i=0;i<8;i++)car(4,-360+i*90,Math.PI/2,0xd35400,true);
let mode='walk',near=null,keys={}; const state={coins:500,dp:300,house:true,car:false,journey:0};
const start=document.createElement('div');start.className='start';start.innerHTML='<div class="startCard"><h1>🏙️ DreamCity</h1><p><b>Phase 1 — Real 3D City Foundation</b></p><p>Yeh playable foundation hai: connected roads, traffic, footpaths, parks, real buildings, NPCs, enterable house aur drivable car.</p><button id="begin">City mein enter karein</button><div class="loading">WASD / Arrow = move · Mouse = camera · E = interact · F = car</div></div>';document.body.appendChild(start);document.getElementById('begin').onclick=()=>start.remove();
const hud=document.createElement('div');hud.className='hud';hud.innerHTML='<div class="top"><div class="pill">🏙️ DreamCity · Phase 1</div><div class="pill">🪙 <span id="coins">500</span> · ⭐ <span id="dp">300</span></div></div><button class="help">❓ Help</button><button class="interact" id="interact">Interact</button><div class="mission"><b id="mission">🎯 Mission: Apne house tak jao aur andar enter karo.</b><span>3D city foundation progress</span><div class="bar"><i id="progress"></i></div></div><div class="modal" id="modal"><div class="card" id="card"></div></div>';document.body.appendChild(hud);
function modal(html){document.getElementById('card').innerHTML=html+'<br><button onclick="document.getElementById(\'modal\').classList.remove(\'open\')">Close</button>';document.getElementById('modal').classList.add('open')}
hud.querySelector('.help').onclick=()=>modal('<h2>🎮 DreamCity Controls</h2><p>WASD / Arrow keys se human move hota hai. Mouse se camera dekhein. Kisi marked building/house ke paas <b>E</b> dabayein.</p><p><b>House:</b> andar enter karke rooms aur furniture dekhein.</p><p><b>Car:</b> car ke paas ja kar F dabayein; phir WASD se drive karein.</p><p>Phase 1 ka target ek connected living-city foundation hai; next phases isi world ko expand karengi.</p>');
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
function enterHouse(){player.visible=false;mode='house';camera.position.set(48,8,50);controls.target.set(38,1,38);document.getElementById('mission').textContent='🏠 House interior: kitchen, living room, bedroom aur furniture explore karein.';document.getElementById('progress').style.width='45%'}
function exitHouse(){player.visible=true;mode='walk';player.position.set(38,0,34);camera.position.set(48,9,58);controls.target.copy(player.position);}
function toggleCar(){if(state.car){mode='walk';state.car=false;player.visible=true;document.getElementById('mission').textContent='🚶 Car se bahar aa gaye. City explore karein.';return}let closest=cars.find(c=>dist(player.position,c.g.position)<5);if(closest){mode='car';state.car=closest;player.visible=false;document.getElementById('mission').textContent='🚗 Car drive karein: WASD / arrows. F se bahar niklein.';}}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e'&&near){if(near==='house')enterHouse();else modal('<h2>'+near+'</h2><p>Yeh building Phase 2 mein fully enterable hogi. Abhi aap is city foundation mein iska exterior dekh sakte hain.</p>')}if(e.key.toLowerCase()==='f')toggleCar()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function updatePlayer(dt){if(mode==='house'){controls.update();return}let dx=0,dz=0;if(keys.w||keys.arrowup)dz-=1;if(keys.s||keys.arrowdown)dz+=1;if(keys.a||keys.arrowleft)dx-=1;if(keys.d||keys.arrowright)dx+=1;if(dx||dz){const l=Math.hypot(dx,dz);dx/=l;dz/=l;const sp=mode==='car'?16:7;const obj=mode==='car'?state.car.g:player;obj.position.x+=dx*sp*dt;obj.position.z+=dz*sp*dt;if(mode==='walk'){player.rotation.y=Math.atan2(dx,dz);const t=performance.now()/100;legs[0].rotation.x=Math.sin(t*.8)*.6;legs[1].rotation.x=-legs[0].rotation.x;arms[0].rotation.x=-legs[0].rotation.x*.7;arms[1].rotation.x=-legs[1].rotation.x*.7}}const obj=mode==='car'?state.car.g:player;controls.target.lerp(new THREE.Vector3(obj.position.x,1.5,obj.position.z),.12);camera.position.lerp(new THREE.Vector3(obj.position.x+12,obj.position.y+9,obj.position.z+15),.04);controls.update();}
function updateTraffic(dt){for(const c of cars){if(!c.ai)continue;if(c.axis==='x'){c.g.position.x+=c.speed*c.dir*dt;if(c.g.position.x>450)c.g.position.x=-450;if(c.g.position.x<-450)c.g.position.x=450}else{c.g.position.z+=c.speed*c.dir*dt;if(c.g.position.z>450)c.g.position.z=-450;if(c.g.position.z<-450)c.g.position.z=450}}npcs.forEach(n=>{n.g.position.x+=Math.sin(performance.now()/3000+n.phase)*n.speed*dt;n.g.position.z+=Math.cos(performance.now()/3400+n.phase)*n.speed*dt})}
function checkNear(){near=null;const p=player.position;if(dist(p,new THREE.Vector3(38,0,31))<6)near='house';else if(mode==='walk'){for(const n of interactables){if(dist(p,n.pos)<5){near=n.name;break}}}const btn=document.getElementById('interact');btn.style.display=near?'block':'none';btn.textContent=near==='house'?'🏠 Enter House':'E Interact';btn.onclick=()=>{if(near==='house')enterHouse();else modal('<h2>'+near+'</h2><p>Building interaction next layer mein unlock hogi.</p>')}}
let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;updatePlayer(dt);updateTraffic(dt);if(mode==='walk')checkNear();renderer.render(scene,camera)}animate(last);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});