// DreamCity gameplay systems — layered on top of the city foundation.
(function(){
  const state={health:100,ammo:12,maxAmmo:12,cash:25000,wanted:0,missionActive:false,missionKills:0,missionGoal:3,missionReward:2500,lastShot:0,fireDelay:180,flashUntil:0,messageUntil:0};
  const hud={health:document.getElementById('healthValue'),healthBar:document.getElementById('healthBar'),ammo:document.getElementById('ammoValue'),cash:document.getElementById('cashValue'),wanted:document.getElementById('wantedValue'),mission:document.getElementById('missionText'),missionPanel:document.getElementById('missionPanel'),message:document.getElementById('gameMessage')};
  const enemies=[],missionTargets=[]; let missionMarker=null,gun=null,flash=null,walkingTime=0,lastFrame=performance.now();
  function message(text,ms=2600){if(!hud.message)return;hud.message.textContent=text;hud.message.classList.add('show');state.messageUntil=performance.now()+ms;}
  function updateHud(){if(hud.health){hud.health.textContent=Math.ceil(state.health);hud.healthBar.style.width=Math.max(0,state.health)+'%';}if(hud.ammo)hud.ammo.textContent=state.ammo+' / '+state.maxAmmo;if(hud.cash)hud.cash.textContent=state.cash.toLocaleString();if(hud.wanted)hud.wanted.textContent=state.wanted?'★'.repeat(state.wanted)+'☆'.repeat(5-state.wanted):'☆☆☆☆☆';if(hud.mission)hud.mission.textContent=state.missionActive?`Street Job: ${state.missionKills}/${state.missionGoal} targets`:'Go to the yellow marker and press E';if(hud.missionPanel)hud.missionPanel.classList.toggle('active',state.missionActive);}
  function makeMat(color,roughness=.65,metalness=0){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
  function createGun(){gun=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.24,.22,.9),makeMat(0x20252a,.35,.25));body.position.set(.46,1.78,.48);gun.add(body);const grip=new THREE.Mesh(new THREE.BoxGeometry(.16,.34,.2),makeMat(0x171b1e,.7));grip.position.set(.46,1.56,.30);grip.rotation.x=-.18;gun.add(grip);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,.62,10),makeMat(0x0c0f11,.25,.45));barrel.rotation.x=Math.PI/2;barrel.position.set(.46,1.78,.98);gun.add(barrel);const muzzle=new THREE.Object3D();muzzle.position.set(.46,1.78,1.30);gun.add(muzzle);flash=new THREE.Mesh(new THREE.SphereGeometry(.13,8,8),new THREE.MeshBasicMaterial({color:0xffd36a}));flash.visible=false;muzzle.add(flash);player.add(gun);}
  function createEnemy(x,z,index){const g=new THREE.Group(),skin=makeMat(0xb97b5c,.8),shirt=makeMat([0x8d3131,0x333f79,0x6d4a31][index%3],.72),dark=makeMat(0x20252b,.75);const head=new THREE.Mesh(new THREE.SphereGeometry(.56,14,10),skin);head.position.y=2.55;g.add(head);const torso=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.45,.62),shirt);torso.position.y=1.45;g.add(torso);const l1=new THREE.Mesh(new THREE.BoxGeometry(.3,1.25,.34),dark);l1.position.set(-.22,.35,0);g.add(l1);const l2=l1.clone();l2.position.x=.22;g.add(l2);const a1=new THREE.Mesh(new THREE.BoxGeometry(.25,1.15,.25),skin);a1.position.set(-.68,1.5,0);g.add(a1);const a2=a1.clone();a2.position.x=.68;g.add(a2);g.position.set(x,0,z);g.userData={health:50,alive:true,home:new THREE.Vector3(x,0,z),phase:index*.8};g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(g);enemies.push(g);missionTargets.push(g);}
  function createEnemies(){[[55,42],[-58,42],[42,-55],[-42,-58],[180,18],[-180,-18],[18,180],[-18,-180]].forEach((p,i)=>createEnemy(p[0],p[1],i));}
  function createMissionMarker(){missionMarker=new THREE.Group();const ring=new THREE.Mesh(new THREE.RingGeometry(2.8,3.5,32),new THREE.MeshBasicMaterial({color:0xffd54f,transparent:true,opacity:.9,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.25;missionMarker.add(ring);const beam=new THREE.Mesh(new THREE.CylinderGeometry(.12,.5,5,12),new THREE.MeshBasicMaterial({color:0xffd54f,transparent:true,opacity:.3}));beam.position.y=2.5;missionMarker.add(beam);missionMarker.position.set(-40,0,38);scene.add(missionMarker);}
  function acceptMission(){if(state.missionActive)return;if(player.position.distanceTo(missionMarker.position)>7){message('Walk to the yellow mission marker first.');return;}state.missionActive=true;state.missionKills=0;missionTargets.length=0;enemies.forEach(e=>{if(e.userData.alive)missionTargets.push(e);});missionMarker.visible=false;state.wanted=1;updateHud();message('MISSION STARTED — take down 3 targets.');}
  function aimHit(){const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const objects=[];enemies.forEach(e=>{if(e.userData.alive)e.traverse(o=>{if(o.isMesh)objects.push(o);});});const hits=ray.intersectObjects(objects,false);return hits.length?hits[0].object:null;}
  function findEnemy(object){let o=object;while(o&&o.userData&&o.userData.health===undefined)o=o.parent;return o&&o.userData&&o.userData.health!==undefined?o:null;}
  function shoot(){const now=performance.now();if(now-state.lastShot<state.fireDelay)return;if(state.ammo<=0){message('Out of ammo — press R to reload.');return;}state.lastShot=now;state.ammo--;state.wanted=Math.min(5,Math.max(state.wanted,1));if(flash){flash.visible=true;state.flashUntil=now+55;}const hit=aimHit(),target=hit?findEnemy(hit):null;if(target&&target.userData.alive){target.userData.health-=25;if(target.userData.health<=0)killEnemy(target);else message('HIT — 25 damage',700);}updateHud();}
  function killEnemy(enemy){if(!enemy.userData.alive)return;enemy.userData.alive=false;const pos=enemy.position.clone();enemy.visible=false;state.wanted=Math.min(5,state.wanted+1);if(state.missionActive&&missionTargets.includes(enemy)){state.missionKills++;if(state.missionKills>=state.missionGoal){state.missionActive=false;state.cash+=state.missionReward;state.wanted=0;missionMarker.visible=true;message('MISSION COMPLETE — +$2,500',4200);}}const puff=new THREE.Mesh(new THREE.SphereGeometry(.35,10,8),new THREE.MeshBasicMaterial({color:0x8c98a0,transparent:true,opacity:.65}));puff.position.copy(pos);scene.add(puff);let t=0;const fade=()=>{t+=.05;puff.scale.multiplyScalar(1.08);puff.material.opacity*=.9;if(t<1)requestAnimationFrame(fade);else scene.remove(puff);};fade();updateHud();}
  function reload(){if(state.ammo===state.maxAmmo){message('Magazine already full.',1000);return;}message('RELOADING...',900);setTimeout(()=>{state.ammo=state.maxAmmo;updateHud();message('RELOADED',1000);},900);}
  function animateWorld(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;const moving=(keys.w||keys.a||keys.s||keys.d||keys.arrowup||keys.arrowdown||keys.arrowleft||keys.arrowright);if(moving)walkingTime+=dt*(keys.shift?13:8);player.position.y=moving?Math.sin(walkingTime)*.035:Math.sin(now*.001)*.008;if(gun)gun.rotation.x=moving?Math.sin(walkingTime)*.025:0;enemies.forEach(e=>{if(!e.userData.alive)return;const h=e.userData.home,p=e.userData.phase;e.position.x=h.x+Math.sin(now*.00035+p)*3.2;e.position.z=h.z+Math.cos(now*.00028+p)*2.6;e.rotation.y=Math.sin(now*.00035+p);const swing=Math.sin(now*.006+p)*.35;if(e.children[2])e.children[2].rotation.x=swing;if(e.children[3])e.children[3].rotation.x=-swing;});if(missionMarker&&missionMarker.visible){missionMarker.rotation.y+=dt*.8;missionMarker.position.y=Math.sin(now*.002)*.08;}if(flash&&now>state.flashUntil)flash.visible=false;if(hud.message&&now>state.messageUntil)hud.message.classList.remove('show');updateHud();requestAnimationFrame(animateWorld);}
  function bind(){if(!window.THREE)return setTimeout(bind,100);createGun();createEnemies();createMissionMarker();updateHud();document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='r')reload();if(k==='e')acceptMission();if(e.key==='escape')document.exitPointerLock?.();});renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)shoot();});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());message('Welcome to DreamCity — explore the city or start a mission.',3500);requestAnimationFrame(animateWorld);}
  bind();
})();
